version: "3.9"

services:
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis_data:/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redcollector-app
    env_file:
      - ./.env
    volumes:
      - ./:/srv/app
    depends_on:
      - redis
    ports:
      - "8000:80"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redcollector-worker
    env_file:
      - ./.env
    volumes:
      - ./:/srv/app
    depends_on:
      - redis
      - app
    restart: unless-stopped
    command: ["python", "manage.py", "run-worker"]